param(
    [string]$Source = "$HOME\.codex\safety-policy.json",
    [string]$CodexTarget = "$HOME\.codex\deny-patterns.yaml",
    [string]$ClaudeTarget = "$HOME\.claude\deny-patterns.json",
    [switch]$ImportExisting,
    [switch]$Write,
    [switch]$Check
)

$ErrorActionPreference = "Stop"

# Check는 비변경 검사다. 쓰기 옵션과 함께 지정하면 아무것도 쓰기 전에 거부한다.
if ($Check -and ($Write -or $ImportExisting)) { throw "-Check는 -Write 또는 -ImportExisting과 함께 사용할 수 없습니다." }

function Read-CodexEntries([string]$Path) {
    $entries = @()
    $current = $null
    foreach ($line in Get-Content -LiteralPath $Path -Encoding UTF8) {
        if ($line -match '^\s*- pattern:\s*"(.*)"\s*$') {
            if ($null -ne $current) { $entries += [pscustomobject]$current }
            $current = [ordered]@{ pattern = $Matches[1] }
            continue
        }
        if ($null -eq $current) { continue }
        if ($line -match '^\s+policy:\s*"(.*)"\s*$') { $current.policy = $Matches[1] }
        elseif ($line -match "^\s+tokens:\s*'(.*)'\s*$") { $current.tokens = @((ConvertFrom-Json -InputObject $Matches[1])) }
        elseif ($line -match '^\s+scope:\s*"(.*)"\s*$') { $current.scope = $Matches[1] }
        elseif ($line -match '^\s+reason:\s*"(.*)"\s*$') { $current.reason = $Matches[1] }
    }
    if ($null -ne $current) { $entries += [pscustomobject]$current }
    return $entries
}

function New-CodexYaml([object[]]$Entries) {
    $lines = @(
        "# AUTO-GENERATED by tools/sync-global-safety-policy.ps1. 직접 수정하지 않는다.",
        "# 공통 원본: safety-policy.json",
        "patterns:"
    )
    foreach ($entry in $Entries) {
        if ($entry.policy -notin @("forbidden", "prompt", "scan")) { throw "잘못된 Codex policy: $($entry.policy)" }
        $lines += "  - pattern: `"$($entry.pattern)`""
        $lines += "    policy: `"$($entry.policy)`""
        if ($entry.policy -ne "scan") {
            if (@($entry.tokens).Count -eq 0) { throw "Codex 명령 정책에 tokens가 없습니다: $($entry.pattern)" }
            $tokensJson = ConvertTo-Json -InputObject @($entry.tokens) -Compress
            $lines += "    tokens: '$tokensJson'"
        }
        $lines += "    scope: `"$($entry.scope)`""
        $lines += "    reason: `"$($entry.reason)`""
        $lines += ""
    }
    return ($lines -join "`n").TrimEnd() + "`n"
}

function New-ClaudeJson([object[]]$Patterns) {
    $document = [ordered]@{ version = 1; patterns = @($Patterns) }
    return (ConvertTo-Json -InputObject $document -Depth 20) + "`n"
}

function Test-JsonValueEqual([object]$Left, [object]$Right) {
    if ($null -eq $Left -or $null -eq $Right) { return ($null -eq $Left -and $null -eq $Right) }
    # 객체의 속성 순서는 무시하되 이름의 대소문자와 누락·추가 속성은 구분한다.
    if ($Left -is [pscustomobject] -and $Right -is [pscustomobject]) {
        $leftProperties = @($Left.PSObject.Properties)
        $rightNames = @($Right.PSObject.Properties.Name)
        if ($leftProperties.Count -ne $rightNames.Count) { return $false }
        foreach ($property in $leftProperties) {
            if ($rightNames -cnotcontains $property.Name) { return $false }
            if (-not (Test-JsonValueEqual $property.Value $Right.PSObject.Properties[$property.Name].Value)) { return $false }
        }
        return $true
    }
    # 배열 순서는 정책 검사 순서이므로 보존한다. 값의 형식과 문자열 대소문자도 보존한다.
    if ($Left -is [array] -and $Right -is [array]) {
        if ($Left.Count -ne $Right.Count) { return $false }
        for ($index = 0; $index -lt $Left.Count; $index++) {
            if (-not (Test-JsonValueEqual $Left[$index] $Right[$index])) { return $false }
        }
        return $true
    }
    if ($Left.GetType() -ne $Right.GetType()) { return $false }
    return ($Left -ceq $Right)
}

function Write-Utf8Bom([string]$Path, [string]$Content) {
    [System.IO.File]::WriteAllText($Path, $Content, [System.Text.UTF8Encoding]::new($true))
}

function Write-Utf8NoBom([string]$Path, [string]$Content) {
    [System.IO.File]::WriteAllText($Path, $Content, [System.Text.UTF8Encoding]::new($false))
}

if ($ImportExisting) {
    $claude = Get-Content -Raw -LiteralPath $ClaudeTarget -Encoding UTF8 | ConvertFrom-Json
    $sourceDocument = [ordered]@{
        schemaVersion = 1
        description = "Codex와 Claude 글로벌 안전 정책의 단일 원본"
        platformPolicies = [ordered]@{
            codex = [ordered]@{ entries = @(Read-CodexEntries $CodexTarget) }
            claude = [ordered]@{ patterns = @($claude.patterns) }
        }
    }
    Write-Utf8Bom $Source ((ConvertTo-Json -InputObject $sourceDocument -Depth 20) + "`n")
    Write-Output "IMPORT: $Source"
}

$policy = Get-Content -Raw -LiteralPath $Source -Encoding UTF8 | ConvertFrom-Json
if ($policy.schemaVersion -ne 1) { throw "지원하지 않는 안전 정책 버전: $($policy.schemaVersion)" }
$codexEntries = @($policy.platformPolicies.codex.entries)
$claudePatterns = @($policy.platformPolicies.claude.patterns)
if ($codexEntries.Count -eq 0 -or $claudePatterns.Count -eq 0) { throw "플랫폼 안전 정책이 비어 있습니다." }

$codexOutput = New-CodexYaml $codexEntries
$claudeOutput = New-ClaudeJson $claudePatterns
if ($Write) {
    # 한쪽 산출물만 갱신되지 않도록 모든 출력 경로를 쓰기 전에 확인한다.
    foreach ($target in @($CodexTarget, $ClaudeTarget)) {
        $parent = Split-Path -Parent ([System.IO.Path]::GetFullPath($target))
        if (-not (Test-Path -LiteralPath $parent -PathType Container)) { throw "출력 폴더가 없습니다: $parent" }
        if (Test-Path -LiteralPath $target -PathType Container) { throw "출력 경로가 폴더입니다: $target" }
    }
    Write-Utf8Bom $CodexTarget $codexOutput
    # Node JSON.parse 호환을 위해 Claude 정책 JSON에는 BOM을 넣지 않는다.
    Write-Utf8NoBom $ClaudeTarget $claudeOutput
    Write-Output "SYNC: Codex=$($codexEntries.Count), Claude=$($claudePatterns.Count)"
}
elseif ($Check) {
    $currentCodex = (Get-Content -Raw -LiteralPath $CodexTarget -Encoding UTF8).Replace("`r`n", "`n")
    $currentClaude = Get-Content -Raw -LiteralPath $ClaudeTarget -Encoding UTF8
    if ($currentCodex -ne $codexOutput.Replace("`r`n", "`n")) { throw "Codex 안전 정책 드리프트" }
    # 같은 런타임에서 파싱해 들여쓰기·개행·이스케이프 표현 차이만 허용한다.
    # 루트는 객체여야 한다. PowerShell의 단일 원소 배열 자동 펼침과 빈 파일을 허용하지 않는다.
    if ($currentClaude -notmatch '^\s*\{') { throw "Claude 안전 정책은 JSON 객체여야 합니다." }
    $currentDocument = ConvertFrom-Json -InputObject $currentClaude
    $expectedDocument = ConvertFrom-Json -InputObject $claudeOutput
    if (-not (Test-JsonValueEqual $currentDocument $expectedDocument)) { throw "Claude 안전 정책 드리프트" }
    Write-Output "PASS: 공통 안전 원본과 플랫폼 산출물 일치"
}
else {
    Write-Output "INFO: -ImportExisting, -Write 또는 -Check를 지정하세요."
}
