param(
    [string]$Source = "$HOME\.codex\safety-policy.json",
    [string]$CodexTarget = "$HOME\.codex\deny-patterns.yaml",
    [string]$ClaudeTarget = "$HOME\.claude\deny-patterns.json",
    [switch]$ImportExisting,
    [switch]$Write,
    [switch]$Check
)

$ErrorActionPreference = "Stop"

function Read-CodexEntries([string]$Path) {
    $entries = @()
    $current = $null
    foreach ($line in Get-Content -LiteralPath $Path -Encoding UTF8) {
        if ($line -match '^\s*- pattern:\s*"(.*)"\s*$') {
            if ($null -ne $current) { $entries += [pscustomobject]$current }
            $current = [ordered]@{ pattern = $Matches[1] }
            continue
        }
        if ($null -eq $current) { continue }
        if ($line -match '^\s+policy:\s*"(.*)"\s*$') { $current.policy = $Matches[1] }
        elseif ($line -match "^\s+tokens:\s*'(.*)'\s*$") { $current.tokens = @((ConvertFrom-Json -InputObject $Matches[1])) }
        elseif ($line -match '^\s+scope:\s*"(.*)"\s*$') { $current.scope = $Matches[1] }
        elseif ($line -match '^\s+reason:\s*"(.*)"\s*$') { $current.reason = $Matches[1] }
    }
    if ($null -ne $current) { $entries += [pscustomobject]$current }
    return $entries
}

function New-CodexYaml([object[]]$Entries) {
    $lines = @(
        "# AUTO-GENERATED by tools/sync-global-safety-policy.ps1. 직접 수정하지 않는다.",
        "# 공통 원본: safety-policy.json",
        "patterns:"
    )
    foreach ($entry in $Entries) {
        if ($entry.policy -notin @("forbidden", "prompt", "scan")) { throw "잘못된 Codex policy: $($entry.policy)" }
        $lines += "  - pattern: `"$($entry.pattern)`""
        $lines += "    policy: `"$($entry.policy)`""
        if ($entry.policy -ne "scan") {
            if (@($entry.tokens).Count -eq 0) { throw "Codex 명령 정책에 tokens가 없습니다: $($entry.pattern)" }
            $tokensJson = ConvertTo-Json -InputObject @($entry.tokens) -Compress
            $lines += "    tokens: '$tokensJson'"
        }
        $lines += "    scope: `"$($entry.scope)`""
        $lines += "    reason: `"$($entry.reason)`""
        $lines += ""
    }
    return ($lines -join "`n").TrimEnd() + "`n"
}

function New-ClaudeJson([object[]]$Patterns) {
    $document = [ordered]@{ version = 1; patterns = @($Patterns) }
    return (ConvertTo-Json -InputObject $document -Depth 20) + "`n"
}

function Write-Utf8Bom([string]$Path, [string]$Content) {
    [System.IO.File]::WriteAllText($Path, $Content, [System.Text.UTF8Encoding]::new($true))
}

function Write-Utf8NoBom([string]$Path, [string]$Content) {
    [System.IO.File]::WriteAllText($Path, $Content, [System.Text.UTF8Encoding]::new($false))
}

if ($ImportExisting) {
    $claude = Get-Content -Raw -LiteralPath $ClaudeTarget -Encoding UTF8 | ConvertFrom-Json
    $sourceDocument = [ordered]@{
        schemaVersion = 1
        description = "Codex와 Claude 글로벌 안전 정책의 단일 원본"
        platformPolicies = [ordered]@{
            codex = [ordered]@{ entries = @(Read-CodexEntries $CodexTarget) }
            claude = [ordered]@{ patterns = @($claude.patterns) }
        }
    }
    Write-Utf8Bom $Source ((ConvertTo-Json -InputObject $sourceDocument -Depth 20) + "`n")
    Write-Output "IMPORT: $Source"
}

$policy = Get-Content -Raw -LiteralPath $Source -Encoding UTF8 | ConvertFrom-Json
if ($policy.schemaVersion -ne 1) { throw "지원하지 않는 안전 정책 버전: $($policy.schemaVersion)" }
$codexEntries = @($policy.platformPolicies.codex.entries)
$claudePatterns = @($policy.platformPolicies.claude.patterns)
if ($codexEntries.Count -eq 0 -or $claudePatterns.Count -eq 0) { throw "플랫폼 안전 정책이 비어 있습니다." }

$codexOutput = New-CodexYaml $codexEntries
$claudeOutput = New-ClaudeJson $claudePatterns
if ($Write) {
    Write-Utf8Bom $CodexTarget $codexOutput
    # Node JSON.parse 호환을 위해 Claude 정책 JSON에는 BOM을 넣지 않는다.
    Write-Utf8NoBom $ClaudeTarget $claudeOutput
    Write-Output "SYNC: Codex=$($codexEntries.Count), Claude=$($claudePatterns.Count)"
}
elseif ($Check) {
    $currentCodex = (Get-Content -Raw -LiteralPath $CodexTarget -Encoding UTF8).Replace("`r`n", "`n")
    $currentClaude = (Get-Content -Raw -LiteralPath $ClaudeTarget -Encoding UTF8).Replace("`r`n", "`n")
    if ($currentCodex -ne $codexOutput.Replace("`r`n", "`n")) { throw "Codex 안전 정책 드리프트" }
    if ($currentClaude -ne $claudeOutput.Replace("`r`n", "`n")) { throw "Claude 안전 정책 드리프트" }
    Write-Output "PASS: 공통 안전 원본과 플랫폼 산출물 일치"
}
else {
    Write-Output "INFO: -ImportExisting, -Write 또는 -Check를 지정하세요."
}
