param(
    [string]$Source = "$HOME\.codex\deny-patterns.yaml",
    [string]$Target = "$HOME\.codex\rules\deny.rules",
    [switch]$Check
)

$ErrorActionPreference = "Stop"

function Read-PolicyEntries {
    param([string]$Path)

    $entries = @()
    $current = $null

    foreach ($line in Get-Content -LiteralPath $Path -Encoding UTF8) {
        if ($line -match '^\s*- pattern:\s*"(.*)"\s*$') {
            if ($null -ne $current) {
                $entries += [pscustomobject]$current
            }
            $current = @{ Pattern = $Matches[1] }
            continue
        }

        if ($null -eq $current) {
            continue
        }

        if ($line -match '^\s+policy:\s*"(forbidden|prompt|scan)"\s*$') {
            $current.Policy = $Matches[1]
        }
        elseif ($line -match "^\s+tokens:\s*'(.*)'\s*$") {
            $current.TokensJson = $Matches[1]
        }
    }

    if ($null -ne $current) {
        $entries += [pscustomobject]$current
    }

    return $entries
}

function ConvertTo-RuleText {
    param([object[]]$Entries)

    $lines = @(
        "# AUTO-GENERATED by tools/sync-deny-policy.ps1. 직접 수정하지 않는다.",
        "# Source: deny-patterns.yaml",
        ""
    )

    foreach ($entry in $Entries) {
        if ($entry.Policy -eq "scan") {
            continue
        }
        if ([string]::IsNullOrWhiteSpace($entry.TokensJson)) {
            throw "정책 '$($entry.Pattern)'에 tokens가 없습니다."
        }

        $tokens = @((ConvertFrom-Json -InputObject $entry.TokensJson))
        $quotedTokens = $tokens | ForEach-Object {
            '"' + $_.Replace('\', '\\').Replace('"', '\"') + '"'
        }
        $lines += "prefix_rule(pattern=[$($quotedTokens -join ', ')], decision=`"$($entry.Policy)`")"
    }

    return ($lines -join "`n") + "`n"
}

$resolvedSource = (Resolve-Path -LiteralPath $Source).Path
$entries = @(Read-PolicyEntries -Path $resolvedSource)
$generated = ConvertTo-RuleText -Entries $entries

if ($Check) {
    if (-not (Test-Path -LiteralPath $Target)) {
        throw "정책 산출물이 없습니다: $Target"
    }
    $current = Get-Content -Raw -LiteralPath $Target -Encoding UTF8
    if ($current.Replace("`r`n", "`n") -ne $generated) {
        throw "deny.rules가 deny-patterns.yaml과 동기화되지 않았습니다."
    }
    return
}

$targetDirectory = Split-Path -Parent $Target
if (-not (Test-Path -LiteralPath $targetDirectory)) {
    New-Item -ItemType Directory -Path $targetDirectory -Force | Out-Null
}
[System.IO.File]::WriteAllText($Target, $generated, [System.Text.UTF8Encoding]::new($false))
